export const BANKS = [
  { label: '국민은행', value: 'KB' },
  { label: '하나은행', value: 'HN' },
  { label: '신한은행', value: 'SH' },
  { label: '우리은행', value: 'WR' },
  { label: '기업은행', value: 'IB' },
  { label: '농협은행', value: 'NH' },
  { label: '신협은행', value: 'SHB' },
  { label: '부산은행', value: 'BS' },
  { label: '제주은행', value: 'JJ' },
  { label: '경남은행', value: 'GN' },
  { label: '전북은행', value: 'JB' },
  { label: '광주은행', value: 'GJ' },
  { label: '대구은행', value: 'DG' },
  { label: '수협은행', value: 'SU' },
  { label: '새마을금고', value: 'SM' },
  { label: '우체국', value: 'UC' },
  { label: '케이뱅크', value: 'KB' },
  { label: '카카오뱅크', value: 'KK' },
  { label: '토스뱅크', value: 'TS' },
];
